import { provideHttpClient, withFetch } from '@angular/common/http';
import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideIcons } from '@ng-icons/core';
import {
    lucideArrowLeft,
    lucideCheck,
    lucideChevronDown,
    lucideChevronLeft,
    lucideChevronRight,
    lucideChevronsLeft,
    lucideChevronsRight,
    lucideEye,
    lucideEyeOff,
    lucideFile,
    lucideFolderClosed,
    lucideFolderOpen,
    lucideFolderPlus,
    lucideMessageSquare,
    lucideMessageSquareText,
    lucideMonitor,
    lucideMoon,
    lucideBot,
    lucideCheckCheck,
    lucideExternalLink,
    lucideHistory,
    lucidePencil,
    lucideUser,
    lucidePlus,
    lucideReply,
    lucideSave,
    lucideScan,
    lucideSend,
    lucideSettings,
    lucideSun,
    lucideTrash2,
    lucideX,
} from '@ng-icons/lucide';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
    providers: [
        provideBrowserGlobalErrorListeners(),
        provideRouter(routes, withComponentInputBinding()),
        provideZonelessChangeDetection(),
        provideHttpClient(withFetch()),
        provideIcons({
            lucideChevronsRight,
            lucideChevronsLeft,
            lucideChevronLeft,
            lucideChevronRight,
            lucideChevronDown,
            lucideMessageSquare,
            lucideMessageSquareText,
            lucidePlus,
            lucideArrowLeft,
            lucideFolderOpen,
            lucideFolderClosed,
            lucideFile,
            lucidePencil,
            lucideTrash2,
            lucideCheck,
            lucideReply,
            lucideSend,
            lucideSave,
            lucideX,
            lucideSun,
            lucideMoon,
            lucideMonitor,
            lucideSettings,
            lucideEye,
            lucideEyeOff,
            lucideScan,
            lucideFolderPlus,
            lucideExternalLink,
            lucideBot,
            lucideUser,
            lucideHistory,
            lucideCheckCheck,
        }),
    ],
};
